SNS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('post/', include('post.urls', namespace="post")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.user_feed, name='feed'),
    path('write-post/', views.write_post, name='write-post'),
    path('delete-post/<int:post_id>/', views.delete_post, name='delete-post'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit-post'),

    path('search/', views.search, name='post_search'),

    path('<int:post_id>/comment_create',
         views.comment_create, name='comment_create'),
    path('<int:comment_id>/comment_delete',
         views.comment_delete, name='comment_delete'),

    path('post_like/<int:post_id>', views.post_like, name='post_like'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(),
         name='tagged_object_list'),
]

templates/taggit/tag_cloud.html
{% extends "post/base.html" %}
{% load static %}
{% block title %}A-Yo SNS | 태그 모음{% endblock %}


{% block content %}
<div class="container timeline-container" style="max-width: 500px;">
    <div class=" taggit-cloud" style="text-align: center; max-width: 470px; margin-top: 130px;">
        {% load taggit_templatetags2_tags %}
        {% get_tagcloud as tags %} <!--모든 태그 추출해서 tags변수에 할당-->
        {% for tag in tags %}
        <span class="badge rounded-pill bg-warning text-dark"
            style="box-shadow: #0f0f0f 0px 0px 5px; border-radius: 10rem; display: inline-block; font-size: 15px; margin: 5px;">
            <a href="{% url 'post:tagged_object_list' tag.name %}" style="color:black; text-decoration: none;">
                {{ tag.name }}({{ tag.num_times }})
            </a>
        </span>
        {% endfor %}
    </div>
</div>
<div>{% include "post/posts.html" %}</div>
{% endblock %}