SNS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('post/', include('post.urls', namespace="post")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.user_feed, name='feed'),
    path('write-post/', views.write_post, name='write-post'),
    path('delete-post/<int:post_id>/', views.delete_post, name='delete-post'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit-post'),

    path('search/', views.search, name='post_search'),

    path('<int:post_id>/comment_create',
         views.comment_create, name='comment_create'),
    path('<int:comment_id>/comment_delete',
         views.comment_delete, name='comment_delete'),

    path('post_like/<int:post_id>', views.post_like, name='post_like'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(),
         name='tagged_object_list'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('my-posts/', views.my_posts, name="my-posts"),
    path('<int:user_id>/my-posts/', views.edit_profile, name="edit-profile"),
]

post/models.py
import os
from django.conf import settings
from django.db import models
from user import models as user_model
from taggit.managers import TaggableManager


class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(
        auto_now=True)  # 업데이트는 auto_now = True 사용

    class Meta:
        abstract = True


class Post(TimeStamedModel):
    author = models.ForeignKey(
        user_model.User,
        null=True,
        on_delete=models.CASCADE,
        related_name='post_author'
    )
    image = models.ImageField(blank=True, null=True)
    caption = models.TextField(blank=False)
    post_likes = models.ManyToManyField(
        user_model.User, blank=True, related_name='post_like')
    tags = TaggableManager(blank=True)

    @property
    def like_count(self):
        return self.post_likes.count()

    def __str__(self):
        return f"{self.author}: {self.caption}"
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
        super(Post, self).delete(*args, **kargs)


class Comment(TimeStamedModel):
    author = models.ForeignKey(
        user_model.User,
        null=True,
        on_delete=models.CASCADE,
        related_name='comment_author'
    )
    posts = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.CASCADE,
        related_name='comment_post'
    )
    contents = models.TextField(blank=False)

    def __str__(self):
        return f"{self.author}: {self.contents}"

post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    caption = forms.CharField(label='', widget=forms.Textarea(
        attrs={'class': 'caption-contents'}))

    class Meta:
        model = Post  # model은 Post 양식으로 쓰겠다.
        fields = ('caption', 'image','tags')  # 어떤 필드를 입력 받을 지

        labels = {
            "caption": "내용",
            "image": "사진",
            "tags":"태그",
        }

class CommentForm(forms.ModelForm):
    contents = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'input-comment2', 'placeholder':'댓글 달기..'}))

    class Meta:
        model = Comment
        fields = ["contents"]

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.views.generic import ListView, TemplateView
from .forms import PostForm, CommentForm
from .models import Post, Comment
from user.models import User as user_model
from post import models
from post.serializers import PostSerializer
from . import serializers


# Create your views here.


@login_required(login_url='')
def write_post(request):
    """게시글을 작성하는 함수"""
    if request.method == 'GET':
        form = PostForm()
        return render(request, 'post/write-post.html', {'form': form})

    elif request.method == 'POST':
        user = get_object_or_404(user_model, pk=request.user.id)
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            write_post = post_form.save(commit=False)
            write_post.author = user
            write_post.save()
            post_form.save_m2m()
            return redirect('post:feed')
        else:
            return redirect('user:signup')


@login_required(login_url='')
def edit_post(request, post_id):
    """게시글을 수정하는 함수"""
    edit_post = Post.objects.get(id=post_id)
    current_edit_post = edit_post.id

    if request.method == 'GET':
        edit_form = PostForm(instance=edit_post)
        context = {
            'form': edit_form,
            'edit': '수정하기',
        }
        return render(request, 'post/edit-post.html', context)

    elif request.method == 'POST':
        user = get_object_or_404(user_model, pk=request.user.id)
        edit_form = PostForm(request.POST, request.FILES, instance=edit_post)
        if edit_form.is_valid():
            edit_post = edit_form.save(commit=False)
            edit_post.author = user
            edit_post.id = current_edit_post
            edit_post.save()
            return redirect(reverse('post:feed') + "#post-" + str(edit_post.id))


@login_required(login_url='')
def delete_post(request, post_id):
    """게시글을 삭제하는 함수"""
    delete_post = Post.objects.get(id=post_id)
    delete_post.delete()
    return redirect('post:feed')


@login_required(login_url='')
def user_feed(request):
    """피드(홈) 페이지"""
    if request.method == 'GET':
        comment_form = CommentForm()
        post_list = Post.objects.all().order_by('-id')

        serializer = serializers.PostSerializer(post_list, many=True)

        return render(request, 'post/posts.html', {'posts': serializer.data, 'comment_form': comment_form})


@login_required(login_url='')
def search(request):
    """검색 함수"""
    if request.user.is_authenticated:
        if request.method == "GET":
            search_keyword = request.GET.get("q", "")
            comment_form = CommentForm()

            # 검색어가 포함된 caption과 username을 모두 찾음
            posts = Post.objects.filter(Q(caption__contains=search_keyword) | Q(
                author__username__contains=search_keyword))

            serializer = serializers.PostSerializer(posts, many=True)
            return render(request, 'post/posts.html', {'posts': serializer.data, 'comment_form': comment_form})


@login_required(login_url='')
def comment_create(request, post_id):
    """댓글 작성 함수"""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.posts = post
        comment.save()

        return redirect(reverse('post:feed') + "#comment-" + str(comment.id))

    else:
        post_list = Post.objects.all().order_by('-id')
        comment_form = CommentForm()

        return render(request, 'post/posts.html', {'posts': post_list, 'comment_form': comment_form})


@login_required(login_url='')
def comment_delete(request, comment_id):
    """댓글 삭제 함수"""
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        comment.delete()

    return redirect(reverse('post:feed'))


@login_required(login_url='')
def post_like(request, post_id):
    """좋아요 함수"""
    response_body = {"result": ""}

    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        like_user = post.post_likes.filter(pk=request.user.id).exists()
        if like_user:
            post.post_likes.remove(request.user)
            result = 'dislike'
        else:
            post.post_likes.add(request.user)
            result = 'like'

        response_body = {
            'result': result,
            'like_count': post.like_count,
        }
        post.save()
        # https://developer.mozilla.org/ko/docs/Web/HTTP/Status
        return JsonResponse(status=200, data=response_body)


# 태그 추가해줄 함수들
class TagCloudTV(TemplateView):
    template_name = 'taggit/tag_cloud.html'


class TaggedObjectLV(ListView):
    template_name = 'post/posts.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tagname"] = self.kwargs["tag"]
        context["posts"] = serializers.PostSerializer(
            context["object_list"], many=True).data

        return context

templates/post/nav.html
{% load static %}

<aside class="left-aside">
    <div class="aside-box">
        <div class="nav-box">
            <div class="logo-bax">
                <div class="logo">
                    <a href="{% url 'post:feed' %}"><img src="{% static 'images/post/mainlogo.png' %}" alt="logo" /></a>
                </div>
            </div>
            <div>
                <div class="menu-box">
                    <div class="nav-content">
                        <a href="{% url 'post:feed' %}">
                            <div class="nav-content2">
                                <div class="nav-content-icon">
                                    <svg aria-label="홈" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" height="24" role="img"
                                        viewBox="0 0 24 24" width="24">
                                        <path
                                            d="M22 23h-6.001a1 1 0 0 1-1-1v-5.455a2.997 2.997 0 1 0-5.993 0V22a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V11.543a1.002 1.002 0 0 1 .31-.724l10-9.543a1.001 1.001 0 0 1 1.38 0l10 9.543a1.002 1.002 0 0 1 .31.724V22a1 1 0 0 1-1 1Z">
                                        </path>
                                    </svg>
                                </div>
                                <div class="nav-content-name">홈</div>
                            </div>
                        </a>
                    </div>
                    <div class="nav-content">
                        <a href="{% url 'user:my-posts' %}">
                            <div class="nav-content2">
                                <div class="nav-content-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="rgb(0, 0, 0)"
                                        class="bi bi-person-circle" viewBox="0 0 16 16">
                                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                        <path fill-rule="evenodd"
                                            d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                    </svg>
                                </div>
                                <div class="nav-content-name">마이페이지</div>
                            </div>
                        </a>
                    </div>
                    <div class="nav-content">
                        <a href="{% url 'post:write-post' %}">
                            <div class="nav-content2">
                                <div class="nav-content-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="rgb(0, 0, 0)"
                                        class="bi bi-file-word" viewBox="0 0 16 16">
                                        <path
                                            d="M4.879 4.515a.5.5 0 0 1 .606.364l1.036 4.144.997-3.655a.5.5 0 0 1 .964 0l.997 3.655 1.036-4.144a.5.5 0 0 1 .97.242l-1.5 6a.5.5 0 0 1-.967.01L8 7.402l-1.018 3.73a.5.5 0 0 1-.967-.01l-1.5-6a.5.5 0 0 1 .364-.606z" />
                                        <path
                                            d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z" />
                                    </svg>
                                </div>
                                <div class="nav-content-name">글쓰기</div>
                            </div>
                        </a>
                    </div>
                    <div class="nav-content">
                        <div class="nav-content2">
                            <div class="nav-content-icon">
                                <svg aria-label="검색" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)" height="24" role="img"
                                    viewBox="0 0 24 24" width="24">
                                    <path d="M19 10.5A8.5 8.5 0 1 1 10.5 2a8.5 8.5 0 0 1 8.5 8.5Z" fill="none"
                                        stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                        stroke-width="2"></path>
                                    <line fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2" x1="16.511" x2="22" y1="16.511"
                                        y2="22"></line>
                                </svg>
                            </div>
                            <div class="nav-content-name">
                                <form action="{% url 'post:post_search' %}" class="search" method="GET">
                                    <input aria-label="검색" autocapitalize="none" class="search" placeholder="검색"
                                        type="text" name="q">
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="nav-content">
                        <a href="{% url 'post:tag_cloud' %}">
                            <div class="nav-content2">
                                <div class="nav-content-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="rgb(0, 0, 0)"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M3 2v4.586l7 7L14.586 9l-7-7H3zM2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2z" />
                                        <path
                                            d="M5.5 5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm0 1a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z" />
                                    </svg>
                                </div>
                                <div class="nav-content-name">태그 모음</div>
                            </div>
                        </a>
                    </div>
                    <div class="nav-content">
                        <a href="{% url 'user:logout' %}">
                            <div class="nav-content2">
                                <div class="nav-content-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="rgb(0, 0, 0)"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                        <path
                                            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                                    </svg>
                                </div>
                                <div class="nav-content-name">로그아웃</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</aside>

templates/post/post_modal.html
{% load static %}


<div id="modal_comment_view" class="modal_overlay">
    <div class="modal_window">
        <!-- 모달 위에 메뉴 -->
        <div class="modal_title">
            <div class="modal_title_side"></div>
            <div>post</div>
            <div class="modal_title_side">
                <span id="close_modal" class="material-icons-outlined">
                    <svg aria-label="닫기" class="x1lliihq x1n2onr6" color="rgb(38, 38, 38)" fill="rgb(255, 255, 255)" height="18" role="img" viewBox="0 0 24 24" width="18"><title>닫기</title><polyline fill="none" points="20.643 3.357 12 12 3.353 20.647" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></polyline><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" x1="20.649" x2="3.354" y1="20.649" y2="3.354"></line></svg>
                </span>
            </div>
        </div>

        <div class="modal_post_box">
            <!-- 사진 노출 부분 -->
            <div class="modal_post_image">
                <img src="/static/images/post/mainlogo.png" alt="post-image" crossorigin="anonymous" decoding="auto" sizes="468px"
                    style="object-fit: cover" />
            </div>
            <!-- 댓글 모아보기 -->
            <div class="modal_comment_box">
                <div class="modal_comment_box2">
                  <div class="modal_comment_box3">
                    <div class="modal_comment_title">
                      <!-- 글쓴이 헤더 -->
                      <div class="modal_comment_title2">
                        사진
                      </div>
                      <div class="modal_comment_title2" id="author_username">
                        
                      </div>
                      <div class="modal_comment_title2" id="post_create_at">
                        글쓴 시간
                      </div>
                    </div>
                    <!-- 댓글 보기 -->
                    <div>
                        <!-- 좋아요&댓글 플렉스 -->
                        <div>
                            <!-- 댓글 & 삭제 플랙스 -->
                            <div class="modal_comment_content">
                                <!-- 댓글 쓴 사람 -->
                                <div class="modal_comment_user">
                                    <a href="">
                                        <!-- {{ comment.author.username }} -->
                                        댓글쓴이
                                    </a>
                                </div>
                                <!-- 댓글 내용 -->
                                <div class="modal_comment_user_content">
                                    <!-- {{ comment.contents }} -->
                                    댓글 내용
                                </div>
                            </div>
                            <!-- 댓글 삭제 버튼 -->
                            <div>
                                <!-- {% if user.id == comment.author.id %} -->
                                <a href="{% url 'post:comment_delete' comment.id %}" onclick="return confirm('삭제할까요?');">
                                  <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="16"
                                    height="16"
                                    fill="currentColor"
                                    class="bi bi-trash3"
                                    viewBox="0 0 16 16"
                                  >
                                    <path
                                      d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"
                                    />
                                  </svg>
                                </a>
                                <!-- {% endif %} -->
                            </div>
                        </div>
                    </div>
                    
                  </div>
                    
                    <div class="modal_like_box">
                        <div>
                            좋아요 몇개
                        </div>
                        <button class="modal_like_button" id="like-button-{{ post.id }}" type="button" onclick="likeClick(this.id)">
                            {% if user.id in post.image_likes %}
                            <div  id="like-{{ post.id }}">
                              <span class="like" style="display: flex;" id="like_button_{{ post.id }}">
                                <svg aria-label="좋아요 취소" class="x1lliihq x1n2onr6" color="rgb(255, 48, 64)" fill="rgb(255, 48, 64)" height="24" role="img" viewBox="0 0 48 48" width="24"><title>좋아요 취소</title><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                              </span>
                              <span class="dislike" style="display: none;" id="dislike_button_{{ post.id }}">
                                <svg aria-label="좋아요" class="x1lliihq x1n2onr6" color="rgb(38, 38, 38)" fill="rgb(38, 38, 38)" height="24" role="img" viewBox="0 0 24 24" width="24"><title>좋아요</title><path d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z"></path></svg>
                              </span>
                            </div>
                            {% else %}
                            <div  id="{{ post.id }}" >
                              <span class="like" style="display: none;" id="like_button_{{ post.id }}">
                                <svg aria-label="좋아요 취소" class="x1lliihq x1n2onr6" color="rgb(255, 48, 64)" fill="rgb(255, 48, 64)" height="24" role="img" viewBox="0 0 48 48" width="24"><title>좋아요 취소</title><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                              </span>
                              <span class="dislike" style="display: flex;" id="dislike_button_{{ post.id }}">
                                <svg aria-label="좋아요" class="x1lliihq x1n2onr6" color="rgb(38, 38, 38)" fill="rgb(38, 38, 38)" height="24" role="img" viewBox="0 0 24 24" width="24"><title>좋아요</title><path d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z"></path></svg>
                              </span>
                            </div>
                            {% endif %}
                        </button>
                        <!-- 댓글 입력창 -->
                        <section class="modal_comment_input_box">
                            <div class="modal_input_form">
                              <form class="input-comment" action="#" method="POST">
                                {% csrf_token %}
                                {{ comment_form }}
                              </form>
                            </div>
                          </section>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

templates/post/write-post.html
{% extends "post/base.html" %}

{% load static %}
{% block title %}A-Yo SNS | 글쓰기{% endblock %}

{% block content %}

<body>
    <div class="container timeline-container">
        <div class="d-flex justify-content-center">
            <div class="col-md-7">
                <div class="row mb-2">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="media">
                                    <div class="media-body">
                                        <h5 class="mt-0">당신의 일상을 공유해 보세요</h5>
                                        <form action="{% url 'post:write-post' %}" method="POST"
                                            enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {{ form.as_p }}


                                            <div class="write-post-back">
                                                {% if edit %}
                                                <input type="submit" class="btn btn-primary" style="float:right;"
                                                    value="수정하기">
                                                {% else %}
                                                <input type="submit" class="btn btn-primary" style="float:right;"
                                                    value="작성하기">
                                                {% endif %}
                                                <a href="{% url 'post:feed' %}">뒤로가기</a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    {% endblock content %}