SNS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('post/', include('post.urls', namespace="post")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.user_feed, name='feed'),
    path('write-post/', views.write_post, name='write-post'),
    path('delete-post/<int:post_id>/', views.delete_post, name='delete-post'),
    path('edit-post/<int:post_id>/', views.edit_post, name='edit-post'),

    path('search/', views.search, name='post_search'),

    path('<int:post_id>/comment_create',
         views.comment_create, name='comment_create'),
    path('<int:comment_id>/comment_delete',
         views.comment_delete, name='comment_delete'),

    path('post_like/<int:post_id>', views.post_like, name='post_like'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(),
         name='tagged_object_list'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('my-posts/', views.my_posts, name="my-posts"),
    path('<int:user_id>/my-posts/', views.edit_profile, name="edit-profile"),
]

user/models.py
import os
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo = models.ImageField(blank=True, null=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)

    class Meta:
        db_table = "my_user"

    def get_absolute_url(self):
        return reverse("users:login", kwargs={"username": self.username})

    def delete(self, *args, **kargs):
        if self.profile_photo:
            os.remove(os.path.join(
                settings.MEDIA_ROOT, self.profile_photo.path))
        super(User, self).delete(*args, **kargs)

user/forms.py
from django.contrib.auth import get_user_model
from django import forms as django_forms
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']

        widgets = {
            'email': django_forms.TextInput(attrs={'class': 'get-input', 'placeholder': '이메일 주소'}),
            'name': django_forms.TextInput(attrs={'class': 'get-input', 'placeholder': '성명'}),
            'username': django_forms.TextInput(attrs={'class': 'get-input', 'placeholder': '아이디'}),
            'password': django_forms.PasswordInput(attrs={'class': 'get-input', 'placeholder': '비밀번호'}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserUpdateForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['profile_photo', 'name', 'user_name', 'bio', 'email']
        labels = {
            'profile_photo': '프로필사진',
            'name': '이름',
            'user_name': '닉네임',
            'bio': '소개',
            'email': '이메일',
        }

        widgets = {
            'profile_photo': django_forms.FileInput(attrs={'id': 'input-image'}),
            'name': django_forms.TextInput(attrs={'class': 'profile-detail-input', 'placeholder': '성명'}),
            'user_name': django_forms.TextInput(attrs={'class': 'profile-detail-input', 'placeholder': '닉네임'}),
            'bio': django_forms.Textarea(attrs={'class': 'profile-detail-input', 'placeholder': '자기 소개'}),
            'email': django_forms.TextInput(attrs={'class': 'profile-detail-input', 'placeholder': '이메일 주소'}),
        }

user/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .models import User as models_user
from post import models
from post.serializers import PostSerializer
from post.forms import CommentForm
from .forms import SignUpForm
from .forms import UserUpdateForm
from django.contrib import messages


def main(request):
    """로그인 함수"""
    if request.method == 'GET':
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('post:feed'))

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('post:feed'))

    return render(request, 'user/main.html')


def signup(request):
    """회원가입 함수"""
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'user/signup.html', {'form': form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('post:feed'))
        return render(request, 'user/signup.html', {'form': form})


@login_required
def logout(request):
    """로그아웃 함수"""
    auth.logout(request)
    return render(request, 'user/main.html')


@login_required
def my_posts(request):
    """내가 쓴 글만 보여주는 함수"""
    if request.method == 'GET':
        comment_form = CommentForm()
        user = get_object_or_404(models_user, pk=request.user.id)
        post_list = models.Post.objects.filter(author=user).order_by('-id')
        serializer = PostSerializer(post_list, many=True)

        return render(request, 'post/posts.html', {'posts': serializer.data, 'comment_form': comment_form, 'user': user})


@login_required
def edit_profile(request, user_id):
    """프로필 수정 함수"""
    user = get_object_or_404(models_user, pk=user_id)
    if user:
        # 로그인한 유저가 맞다면
        if request.method == "GET":
            form = UserUpdateForm(instance=user)
            context = {
            'form': form,
            'edit': '수정하기',
        }
            return render(request, 'user/profile_edit.html', context)
        
        elif request.method == "POST":
            forms = UserUpdateForm(request.POST, request.FILES, instance=user)
            if forms.is_valid():
                forms.save()

            return redirect(reverse('post:feed'))

    else:
        # 로그인한 유저와 다르면
        return redirect('post:feed')

templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- 폰트 -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
    rel="stylesheet" />
  <!-- css 시트 -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/user/main.css' %}" />

  <title>{% block title %}{% endblock title %}A-yo SNS</title>
</head>

<body>
  <div>{% block content %} {% endblock content %}</div>
</body>

</html>

templates/user/main.html
{% extends "user/base.html" %} {% block title %}메인 로그인{% endblock title %}
{% block content %}

<div class="text-center">
  <!-- 구성화면 -->
  <div id="container">
    <div id="borderBox">
      <!-- 로그인 박스 -->
      <div class="loginBox">
        <!-- 대문이름 -->
        <div id="logo">
          <a href="#">A-yo SNS</a>
        </div>
        <!-- 로그인폼 -->
        <div id="login_text">
          <form action="{% url 'user:main' %}" method="POST" id="loginForm">
            {% csrf_token %}
            <!-- 아이디 입력창 -->
            <div class="input-aria">
              <div class="input-info">
                <input type="input" name="username" placeholder="아이디" class="get-input">
              </div>
            </div>
            <!-- 비밀번호 입력창 -->
            <div class="input-aria">
              <div class="input-info">
                <input type="password" name="password" placeholder="비밀번호" class="get-input">
              </div>
            </div>
            <!-- 로그인버튼 -->
            <div id="btnStyle">
              <button type="submit" id="btnStyle2">
                <div id="btnStyle3">로그인</div>
              </button>
            </div>
          </form>
        </div>
      </div>
      <!-- 회원가입 링크 박스 -->
      <div class="loginBox">
        <span>
          <p id="signup-p">
            계정이 없으신가요?
            <a href="{% url 'user:signup' %}" role="link" tabindex="0">가입하기</a>
          </p>
        </span>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/user/profile_detail.html
{% extends "post/base.html" %}

{% load static %}
{% block title %}마이페이지{% endblock title %}
{% block content %}

<div>{% include "user/profile_views.html" %}</div>

<main class="container">
  {% for post in posts %}
  <section id="post-form">
    <div id="post-main">
      <div id="post-main2">
        <div id="post-main3">
          <div id="post-main4">
            <article id="post-form2">
              <div id="post-content">
                <!-- 작성자정보 -->
                <div id="post-create-user">
                  <header id="post-user">
                    {% if post.author.profile_photo %}
                    <a href="#">
                      <span class="photo2">
                        <img src="{{ post.author.profile_photo.url }}" alt="profile-photo"
                          style="height: 42px; width: 42px" />
                      </span>
                    </a>
                    {% else %}
                    <a href="#">
                      <span class="photo2">
                        <img src="{% static 'images/post/noavatar.png' %}" alt="profile-no-photo"
                          style="height: 42px; width: 42px" />
                      </span>
                    </a>
                    {% endif %}
                    <div class="profile-name">
                      <div class="profile-username">
                        {{ post.author.username }}
                      </div>
                      <div class="profile-at">
                        <span>•</span>{{ post.create_at|timesince }} 전
                      </div>
                    </div>
                  </header>
                </div>
              </div>
              <!-- 피드화면 -->
              <div class="post-image1">
                {% if post.image %}
                <div class="post-image2">
                  <img src="{{ post.image.url }}" alt="post-image" crossorigin="anonymous" decoding="auto" sizes="468px"
                    style="object-fit: cover" />
                </div>
                {% else %}
                <div class="post-image2">
                  <img src="{% static 'images/post/mainlogo.png' %}" alt="post-image" crossorigin="anonymous"
                    decoding="auto" sizes="468px" style="object-fit: cover" />
                </div>
                {% endif %}
              </div>
              <div class="comment-box1">
                <div class="comment-box2">
                  <section class="like-i">
                    <span class="like-i2">
                      <button class="like-i3">
                        {% if user.id in post.image_likes %}
                        <div class="bi-heart2">
                          <svg class="x1lliihq x1n2onr6" color="rgb(142, 142, 142)" fill="rgb(142, 142, 142)"
                            height="24" role="img" viewBox="0 0 24 24" width="24">
                            <path
                              d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z">
                            </path>
                          </svg>
                        </div>
                        {% else %}
                        <div class="bi-heart2">
                          <svg class="x1lliihq x1n2onr6" color="rgb(38, 38, 38)" fill="rgb(38, 38, 38)" height="24"
                            role="img" viewBox="0 0 24 24" width="24">
                            <path
                              d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z">
                            </path>
                          </svg>

                        </div>
                        {% endif %}
                      </button>
                    </span>
                    <span class="like-i2">
                      <button class="like-i3">
                        <div class="bi-heart2">
                          <svg aria-label="댓글 달기" class="x1lliihq x1n2onr6" color="rgb(0, 0, 0)" fill="rgb(0, 0, 0)"
                            height="24" role="img" viewBox="0 0 24 24" width="24">
                            <path d="M20.656 17.008a9.993 9.993 0 1 0-3.59 3.615L22 22Z" fill="none"
                              stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path>
                          </svg>
                        </div>
                      </button>
                    </span>
                  </section>
                  <section class="count-like">
                    <div class="count-like2">
                      <span class="count-like3">좋아요 10만 개</span>
                    </div>
                  </section>
                  <div class="post-caption-box">
                    <div class="post-caption1">
                      <div class="post-author-name2">
                        <div class="post-author-name3">
                          <a href="">{{ post.author.username }}</a>
                        </div>
                        <div class="caption-coment">
                          {{ post.caption }}
                        </div>
                      </div>
                      <div class="post-author-name2">
                        <div class="post-author-name4">
                          <a href="">댓글 작성자</a>
                        </div>
                        <div class="caption-coment2">
                          ---------댓글 내용---------------
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endfor %}
</main>

{% endblock content %}

templates/user/profile_edit.html
{% extends "post/base.html" %}

{% load static %}

{% block content %}

<div class="profile-detail-box">
    <form action="{% url 'user:edit-profile' user.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <img id="preview-image" src="{% static 'images/post/mainlogo.png' %}" alt="dlalwl" class="profile-detail-photo">
        {{ form.as_p }}
        <div class="profile-detail-btn">
            <input type="submit" value="수정하기">
            <a href="{% url 'post:feed' %}">뒤로가기</a>
        </div>
    </form>
</div>




{% endblock content %}

templates/user/profile_views.html
{% load static %}

<div class="profile-box">
    <div class="detail-box">
        <!-- 프로필 사진 -->
        {% if user.profile_photo %}
        <div class="photo-box">
            <img src="{{ user.profile_photo.url }}" alt="profile_photo">
        </div>
        {% else %}
        <div class="photo-box">
            <img src="{% static 'images/post/noavatar.png' %}" alt="profile_photo">
        </div>
        {% endif %}
        <!-- 성명 -->
        <div class="profile-contents">
            이&nbsp;&nbsp;&nbsp;름 : {{ user.name }}
        </div>
        <div class="profile-contents">
            아이디 : {{ user.username }}
        </div>
        <div class="profile-contents">
            닉네임 : {{ user.user_name }}
        </div>
        <div class="profile-contents">
            소&nbsp;&nbsp;&nbsp;개 : {{ user.bio }}
        </div>
        <div class="profile-contents">
            이메일 : {{ user.email }}
        </div>
        <div class="profile-contents2">
            <a href="{% url 'user:edit-profile' user.id %}">
                수정하기
            </a>
        </div>
    </div>
</div>

templates/user/signup.html
{% extends "user/base.html" %}
<h1>users/signup.html 페이지 입니다.</h1>
{% block title %} 회원가입 {% endblock title %}

{% block content %}

<div class="text-center">
  <!-- 구성화면 -->
  <div id="container">
    <div id="borderBox">
      <!-- 회원가입 박스 -->
      <div class="loginBox">
        <!-- 대문이름 -->
        <div id="logo">
          <a href="#">A-yo SNS</a>
        </div>
        <!-- 회원가입폼 -->
        <div id="login_text">
          <form action="{% url 'user:signup' %}" method="POST" id="loginForm">
            <h2 id="desc">친구들의 피드를 보려면 가입하세요.</h2>
            {% csrf_token %}
            {% for field in form %}
            <div class="input-aria">
              <div class="input-info">                
                {{ field }}
              </div>                           
            </div>
            {{ field.errors }} 
            {% endfor %}            
        </div>
        <!-- 회원가입 버튼 -->
        <div id="btnStyle">
          <button type="submit" id="btnStyle2">
            <div id="btnStyle3">회원가입</div>
          </button>
        </div>
        </form>
      </div>
    </div>
    <!-- 로그인 링크 박스 -->
    <div class="loginBox">
      <span id="signup-span">
        <p id="signup-p">
          계정이 있으신가요?
          <a href="{% url 'user:main' %}" role="link">로그인</a>
        </p>
      </span>
    </div>
  </div>
</div>
</div>

{% endblock content %}